### ISSUE TITLE
Seems to be incompatible with loadstone

### ISSUE THREAD

**Issue by ghost** [DiFFoZ/BepInExFasterLoadAssetBundles#12]
My modpack normally sits at 13gb of ram. Installed this mod opened the game for a bit then restarted and didn't notice any substantial difference in ram usage (only a couple hundred mbs less). I then deleted loadstone, deleted this mod, and then reinstalled it as version 0.6.3 instead of 0.6.4 and now my game is sitting at 6b of ram. Not sure if downgrading to .6.3 or loadstone was the culprit, but I am pretty sure it was loadstone. I've been working at this for a day straight and I am too tired to go test it with .6.4 and no loadstone but I thought I'd share here.

**Comment by ghost** [comment]
Okay now it is running at 3.8gb? How is this even possible?

**Comment by DiFFoZ** [comment]
The first start up will always take more RAM (or after updating a lot of mods), because I've made decompression in background.

After all decompression requests your next game start up will be much faster and use a lot less memory.
