### ISSUE TITLE
What happened to LethalPerformance's GitHub page？

### ISSUE THREAD

**Issue by NakiriFox** [DiFFoZ/BepInExFasterLoadAssetBundles#13]
![image](https://github.com/user-attachments/assets/9c257053-c804-4c90-bfcc-2aec5e142ea7)

**Comment by DiFFoZ** [comment]
LP is now closed source

**Comment by NakiriFox** [comment]
> LP is now closed source

Got it.

https://github.com/user-attachments/assets/484a2c53-3468-479e-b274-25918883be36

It seems that there is an issue with the LOD setting of the trees. Setting the LOD distance to double can improve this problem, but it will consume significant performance. Is there a better solution?
