### ISSUE TITLE
Does this override the normal Assetbundle thingy

### ISSUE THREAD

**Issue by CatsArmy** [DiFFoZ/BepInExFasterLoadAssetBundles#2]
do i need to use your mod or does it fully replace the one for all mods if it is installed?

**Comment by CatsArmy** [comment]
also does this work for other bepinex modded unity games?

**Comment by DiFFoZ** [comment]
You need to use mod to get fast boot.

And yes, you can use this mod in any Unity v2022 game with BepInEx (mono v5)
