### ISSUE TITLE
AssetBundle loaded via `UnmanagedMemoryStream` is not cached

### ISSUE THREAD

**Issue by dounai2333** [DiFFoZ/BepInExFasterLoadAssetBundles#3]
I have [BlueArchivePlayerModelReplay](https://thunderstore.io/c/lethal-company/p/MK_MODS/BlueArchivePlayerModelReplay/) installed and things goes slow when loading this mod, also there is no bundle matches in the BepInEx/cache folder.

**Comment by DiFFoZ** [comment]
This is because mod is still in WIP and doesn't cover all assetbundle loading methods

**Comment by CatsArmy** [comment]
will the mod later cover all assetbundle loading methods?

**Comment by DiFFoZ** [comment]
@CatsArmy Yes, it will cover all assetbundle loading! methods

**Comment by DiFFoZ** [comment]
v0.5.0 should now handle all methods of loading bundle

**Comment by CatsArmy** [comment]
> v0.5.0 should now handle all methods of loading bundle

Let's go pog
