### ISSUE TITLE
Doesnt always unbundle assetpacks? (Lethal Company)

### ISSUE THREAD

**Issue by Catpyre** [DiFFoZ/BepInExFasterLoadAssetBundles#8]
I dont know how well this functions on smaller packs but in a modpack with 100+ mods it would often not load a lot of assetpacks, some mods were missing sounds, some mods didnt have entire assetpacks unbundled so things like lethal company moons wouldnt load in giving an error of a missing assetbundle. All these issues were fixed by removing this mod. I'm not sure if there some some incompatability going on or if the amount of mods made it difficult to function.

**Comment by DiFFoZ** [comment]
Probably related to #9
